version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gocritic
    - gosec

formatters:
  enable:
    - gofmt
    - goimports

linters:
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable:
        - shadow
    revive:
      confidence: 0.8
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style

linters:
  exclusions:
    presets:
      - default

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
