package main


























































































}	}		t.Errorf("handler returned wrong status code: got %v want %v", status, http.StatusOK)	if status := rr.Code; status != http.StatusOK {	handler.ServeHTTP(rr, req)	})		w.Write([]byte(`{"status":"ready"}`))		w.WriteHeader(http.StatusOK)	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {	rr := httptest.NewRecorder()	}		t.Fatal(err)	if err != nil {	req, err := http.NewRequest("GET", "/ready", nil)func TestReadyEndpoint(t *testing.T) {}	}		t.Errorf("handler returned unexpected body: got %v want %v", rr.Body.String(), expected)	if rr.Body.String() != expected {	expected := `{"status":"healthy"}`	}		t.Errorf("handler returned wrong status code: got %v want %v", status, http.StatusOK)	if status := rr.Code; status != http.StatusOK {	handler.ServeHTTP(rr, req)	})		w.Write([]byte(`{"status":"healthy"}`))		w.WriteHeader(http.StatusOK)	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {	rr := httptest.NewRecorder()	}		t.Fatal(err)	if err != nil {	req, err := http.NewRequest("GET", "/health", nil)func TestHealthEndpoint(t *testing.T) {}	}		})			}				t.Errorf("getEnv() = %v, want %v", got, tt.want)			if got != tt.want {			got := getEnv(tt.key, tt.defaultValue)			}				defer os.Unsetenv(tt.key)				os.Setenv(tt.key, tt.envValue)			if tt.envValue != "" {		t.Run(tt.name, func(t *testing.T) {	for _, tt := range tests {	}		},			want:         "default",			envValue:     "",			defaultValue: "default",			key:          "TEST_VAR_UNSET",			name:         "returns default when environment variable not set",		{		},			want:         "custom",			envValue:     "custom",			defaultValue: "default",			key:          "TEST_VAR",			name:         "returns environment variable when set",		{	}{		want         string		envValue     string		defaultValue string		key          string		name         string	tests := []struct {func TestGetEnv(t *testing.T) {)	"testing"	"os"	"net/http/httptest"	"net/http"import (package main